language: java
jdk:
  - openjdk8

before_install:
  - scripts/before_install.sh

install:
  - echo "Skip install."

script:
  - scripts/build.sh

addons:
  sonarcloud:
    organization: nblxa
    token:
      secure: "zbY2Gps65LvXhx0w70h5B/+r/A0InCNiic76XY2fI5dsbiYe07fAdUITuRNRNhRK707wsVPfdYv4jlgS/jWesLPoDIFRzInER/ACENezso+TLVT2bVSDovdiu+yOOHHtvlCmWoHGwdJAyvb1OiDeknr6LOA25pEIXTpeBag3qTGwLVTKmMvvVk5C+vgL/Nh+pUS+vRQoj2I5XczBCwZeytnVuhupPP92gOP0cw9LNVElSMUSf9/7XE1stjKLBmyHbvhlnbeL3VcC3mG7H+meTdAd8Q+/M0680FzayJWehNSKda1g+Gqq/sYBK5BJhjvhCEW7bDkgAW4RDTY+ta2V67GUplAx3uAIBsYy0qhrqPS0AH4FIi14Bkr/JscZekBvbweCZDHHOaw0c2KOCyMfKBlDfvsz54QFdNBUW+vwws268EGDiX3CkmzxmvBjTdQeOwABgP14W89vYNH8VfB96jGHaE74xwG26IUYroVhvjhWnpU8yChk21A9NP6YjvJbdvMu3OkdVQDuPD6FRsW6dN1xYe0VuRW/hjZa+3wh+d61l1N2chEfxr5PJTmYXP9kkgSAAPRhKU5+zooWx27OtJqgoK6tY4SokSE8fuWYlN8JuSo7JIz1FHtX53SX55U/wlmnUfyo3Bv3qjZuwk9zpV0T7W/mTUFPJ314VhU8/Sk="

before_deploy:
  - export PROJECT_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

deploy:
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key:
      secure: "waKU/i5KkyU98VByYjUCKjCTHqFhlZWE3razX4iicErPiUXOtuZNrUqUzAluiNzgncJfbEhx0IUmymp1w3lPmCQA/Z5AWhR84EG5KwBfeTqiglya170AYQoxhe0Znoyom5PoQWeUsk/mVhO8OHGQvM+tcSMIN2t35nA1gMb0Z1HWAcapTarMLrHuiMIUw2HpNg5jD3pS7Bi90hlVaVuVhp2haUJbTt8Rt9vIxDs7mHifNCT0UR+jln+5RphHAoXwO88xZXHtqIxmmb+iWoDUdeCBCQSAhD/lzyhqyNK267UZDo8V05nFtwzUWgKGm/0na5rzsZAOEx7KxP21v5+Xt6K9LE3FVon5YHHeY1cW5stp+25spH9BEOfIBPquAJ379TeqZd8Ooh4DQeDqhl4DXokigApvsckLXSyHr3RtqaEeOqXGi8iS0SwlESy2p02qFsvgzwJzf0CNLZYGkgXAtWoAQelRr6OXAR6j+82ehz3Kj7+2lq3hPvv44qhJ3KCtKfoitv3rP6+xlnypsxdKgwtPT1CDlsgRVHhiEiUzLqUK4kscpIXazM7qJu9iC4uGYOewRvrgrVSnFN18o9PVbg1+bSifNl0CoWfhPG9ZlpRdwdseZmGtWiVUr4+3Bi24zRgCf5qSEH8mXdeCc6zV/KhjEK9nX2qabFFfuxR8u4s="
    file:
      - cons-list/target/cons-list-$PROJECT_VERSION.jar
      - cons-list/target/cons-list-$PROJECT_VERSION.jar.asc
      - cons-list/target/cons-list-$PROJECT_VERSION-sources.jar
      - cons-list/target/cons-list-$PROJECT_VERSION-sources.jar.asc
      - cons-list/target/cons-list-$PROJECT_VERSION-javadoc.jar
      - cons-list/target/cons-list-$PROJECT_VERSION-javadoc.jar.asc
    on:
      repo: nblxa/cons-list
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|test/testreleases|release/[0-9]+)$

  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh
    on:
      repo: nblxa/cons-list
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|test/testreleases|release/[0-9]+)$

